export const ProductTechnicalList = [
  { key: "type", placeholder: "IEC:60079-1" },
  { key: "protection", placeholder: "IP65" },
  { key: "gasGroup", placeholder: "IIA/IIB/IIC" },
  { key: "material", placeholder: "Aluminium Alloy LM6" },
  { key: "finish", placeholder: "Epoxy Powder Coated" },
  { key: "hardware", placeholder: "SS 304 bolts" },
  { key: "mounting", placeholder: "Wall / Pole" },
  { key: "cableEntry", placeholder: "4 x 3/4'' NPT" },
  { key: "earthing", placeholder: "2 Nos inside & outside" },
  { key: "typeNumber", placeholder: "EXEC-30-WG" },
  { key: "hsnCode", placeholder: "8536" },
  { key: "terminals", placeholder: "4 sq.mm, 10 nos" },
  { key: "gasket", placeholder: "Neoprene" },
  { key: "plateSize", placeholder: "150x200 mm" },
  { key: "cutoutSize", placeholder: "92x92 mm" },
  { key: "glass", placeholder: "Tempered, 5 mm" },
  { key: "wireGuard", placeholder: "Yes/No" },
  { key: "kW", placeholder: "2.2" },
  { key: "rpm", placeholder: "1440" },
  { key: "size", placeholder: "M20" },
  { key: "HorsePower", placeholder: "3 HP" },
  { key: "rating", placeholder: "415V, 50Hz" },
] as const;
